# Generated by Django 5.0.4 on 2024-05-07 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Категория курса (e.g. 1C - ИТ, 1C - Консалтинг)', max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_value', models.CharField(choices=[('1', '1 - очень плохо'), ('2', '2 - плохо'), ('3', '3 - удовлетворительно'), ('4', '4 - хорошо'), ('5', '5 - отлично')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Краткое описание курса', max_length=1000)),
                ('lasting', models.IntegerField(default=30, help_text='Продолжительность курса, в днях')),
                ('is_selected', models.BooleanField(default=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('added', models.DateField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students_app.category')),
            ],
            options={
                'verbose_name': 'Курс',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('date_of_birth', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photoes/')),
                ('status', models.CharField(choices=[('r', 'requested'), ('a', 'approved'), ('f', 'finished')], default='r', help_text='Статус студента', max_length=50)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students_app.course')),
                ('marks', models.ManyToManyField(to='students_app.mark')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Студент',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма')),
                ('paid_date', models.DateField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.student')),
            ],
            options={
                'verbose_name': 'Оплата',
                'ordering': ['-paid_date'],
            },
        ),
    ]
