# Generated by Django 5.0.4 on 2024-05-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0003_alter_category_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lasting',
            field=models.IntegerField(default=1, help_text='Продолжительность курса, в месяцах'),
        ),
    ]
