# Generated by Django 5.0.4 on 2024-05-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0004_alter_course_lasting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Стоимость курса, в азн', max_digits=8),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark_value',
            field=models.IntegerField(choices=[(1, '1 - очень плохо'), (2, '2 - плохо'), (3, '3 - удовлетворительно'), (4, '4 - хорошо'), (5, '5 - отлично')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='marks',
            field=models.ManyToManyField(blank=True, null=True, to='students_app.mark'),
        ),
    ]
