# Generated by Django 5.0.4 on 2024-05-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0005_alter_course_cost_alter_mark_mark_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-name']},
        ),
        migrations.AlterField(
            model_name='course',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Стоимость в месяц, азн', max_digits=8),
        ),
    ]
