# Generated by Django 5.0.4 on 2024-05-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0007_alter_student_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
        migrations.AddField(
            model_name='payment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='images/files'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.student')),
            ],
        ),
    ]
