# Generated by Django 5.0.4 on 2024-05-18 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0008_remove_student_photo_payment_document_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_date'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['added']},
        ),
        migrations.AddField(
            model_name='review',
            name='added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
