# Generated by Django 5.0.4 on 2024-05-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0009_alter_payment_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['added', '-id']},
        ),
    ]
