# Generated by Django 5.0.4 on 2024-05-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0011_mark_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='description',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
