# Generated by Django 5.0.4 on 2024-05-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0012_mark_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='description',
        ),
    ]
