# Generated by Django 5.0.4 on 2024-05-19 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0013_remove_mark_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='added',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='mark_value',
        ),
        migrations.RemoveField(
            model_name='student',
            name='marks',
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(choices=[(1, '1 - очень плохо'), (2, '2 - плохо'), (3, '3 - удовлетворительно'), (4, '4 - хорошо'), (5, '5 - отлично')])),
                ('added', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_app.student')),
            ],
        ),
    ]
