# Generated by Django 5.0.4 on 2024-05-19 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0014_remove_mark_added_remove_mark_mark_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='added',
            field=models.DateField(default=datetime.date(2024, 5, 19)),
        ),
        migrations.AlterField(
            model_name='performance',
            name='mark',
            field=models.IntegerField(choices=[(5, '5 - отлично'), (4, '4 - хорошо'), (3, '3 - удовлетворительно'), (2, '2 - плохо'), (1, '1 - очень плохо')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')]),
        ),
    ]
