# Generated by Django 5.0.4 on 2024-05-19 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0015_delete_mark_alter_payment_paid_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AlterField(
            model_name='performance',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 18, 50, 24, 554150, tzinfo=datetime.timezone.utc)),
        ),
    ]
