# Generated by Django 5.0.4 on 2024-05-19 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0016_remove_image_title_alter_performance_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(default='no_name', max_length=200),
        ),
        migrations.AlterField(
            model_name='performance',
            name='added',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 18, 54, 12, 57039, tzinfo=datetime.timezone.utc)),
        ),
    ]
