# Generated by Django 5.0.6 on 2024-05-23 09:04

import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0018_remove_performance_added_image_added_image_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-added', '-id']},
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='media/images/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/images/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='performance',
            name='date_of_mark',
            field=models.DateField(default=datetime.datetime(2024, 5, 23, 9, 4, 0, 754678, tzinfo=datetime.timezone.utc)),
        ),
    ]
