# Generated by Django 5.0.4 on 2024-05-25 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0019_alter_image_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_selected',
        ),
        migrations.AlterField(
            model_name='category',
            name='flag',
            field=models.CharField(default='nonamed', help_text='Только латинские символы в нижнем регистре, БЕЗ пробелов', max_length=10, unique=True, verbose_name='Сокращение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Категория курса (e.g. 1C - ИТ, 1C - Консалтинг)', max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='date_of_mark',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 11, 57, 19, 590682, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
