# Generated by Django 5.0.4 on 2024-05-26 11:24

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0020_remove_course_is_selected_alter_category_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performance',
            name='date_of_mark',
            field=models.DateField(default=datetime.datetime(2024, 5, 26, 11, 24, 30, 684057, tzinfo=datetime.timezone.utc)),
        ),
    ]
